#server
server:
  port: 8081
  servlet:
    context-path: /user
  tomcat:
    uri-encoding: utf-8

#spring
spring:
  application:
    name: user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/hui_project?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    initialSize: 2
    maxTotal: 10
    maxActive: 5
    maxWaitMillis: 60000
    maxIdle: 3
    minIdle: 1
    removeAbandonedOnMaintenance: true
    removeAbandonedTimeout: 60
    # ???¨¹????¨°??????¦Ì??????????????????????¦Ë?????
    timeBetweenEvictionRunsMillis: 60000
    # ??????????????????§³??????????¦Ë?????
    minEvictableIdleTimeMillis: 30000
    numTestsPerEvictionRun: 2
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # ??PSCache??????????????????PSCache???§³
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # ???¨¹??????????filters????????????sql???????'wall'????????
    filters: stat,wall,slf4j
    # ???connectProperties????????mergeSql???????SQL???
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # ??????DruidDataSource???????? http://localhost:8080/druid/index.html admin/admin
    useGlobalDataSourceStat: true

  #jpa
  jpa:
    datasource: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
  #redis
  redis:
      # Redis???????????????0??
      database: 0
      # Redis?????????
      host: localhost
      # Redis????????????
      port: 6379
      # Redis?????????????????????
      password:
      # ????????????????????????????????
      jedis:
        pool:
          max-active: 8
          # ??????????????????????????????????
          maxwait: 6000
          # ??????§Ö???????????
          maxidle: 5
          # ??????§Ö???§³????????
          minidle: 1
