netty:
  port: 8707
  boss:
    thread:
      count: 2
  worker:
    thread:
      count: 2
  keepAlive: true
  backlog: 2048

#spring
spring:
  application:
    name: netty
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/hui_project?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    initialSize: 2
    maxTotal: 10
    maxActive: 5
    maxWaitMillis: 60000
    maxIdle: 3
    minIdle: 1
    removeAbandonedOnMaintenance: true
    removeAbandonedTimeout: 60
    # ???��????��??????��??????????????????????��?????
    timeBetweenEvictionRunsMillis: 60000
    # ??????????????????��??????????��?????
    minEvictableIdleTimeMillis: 30000
    numTestsPerEvictionRun: 2
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # ??PSCache??????????????????PSCache???��
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # ???��??????????filters????????????sql???????'wall'????????
    filters: stat,wall,slf4j
    # ???connectProperties????????mergeSql???????SQL???
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # ??????DruidDataSource???????? http://localhost:8080/druid/index.html admin/admin
    useGlobalDataSourceStat: true