#server
server:
  port: 8081
  servlet:
    context-path: /burton-lts
  tomcat:
    uri-encoding: utf-8

#spring
spring:
  application:
    name: lts
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/hui_project?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    initialSize: 2
    maxTotal: 10
    maxActive: 5
    maxWaitMillis: 60000
    maxIdle: 3
    minIdle: 1
    removeAbandonedOnMaintenance: true
    removeAbandonedTimeout: 60
    # ���ü����òŽ���һ�μ�⣬�����Ҫ�رյĿ������ӣ���λ�Ǻ���
    timeBetweenEvictionRunsMillis: 60000
    # ����һ�������ڳ�����С�����ʱ�䣬��λ�Ǻ���
    minEvictableIdleTimeMillis: 30000
    numTestsPerEvictionRun: 2
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # ��PSCache������ָ��ÿ��������PSCache�Ĵ�С
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # ���ü��ͳ�����ص�filters��ȥ�����ؽ���sql�޷�ͳ�ƣ�'wall'���ڷ���ǽ
    filters: stat,wall,slf4j
    # ͨ��connectProperties��������mergeSql���ܣ���SQL��¼
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # �ϲ����DruidDataSource�ļ������ http://localhost:8080/druid/index.html admin/admin
    useGlobalDataSourceStat: true