#server
server:
  port: 8090
  servlet:
    context-path: /mongo
  tomcat:
    uri-encoding: utf-8

#spring
spring:
  application:
    name: mongo
  datasource:
    druid:
      #jdbc配置
      url: jdbc:mysql://106.14.47.3:3306/hui_project?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: mongoitdb@123
      #连接池配置
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      max-active: 100
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: select 1 from dual
      validation-query-timeout: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 100000
      #监控配置WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
        allow: 127.0.0.1
      #配置StatFilter
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 1000
        #配置WallFilter
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: false
            drop-table-allow: false
  #jpa
  jpa:
    datasource: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
#  #redis
#  redis:
#      # Redis���ݿ�������Ĭ��Ϊ0��
#      database: 0
#      # Redis��������ַ
#      host: localhost
#      # Redis���������Ӷ˿�
#      port: 6379
#      # Redis�������������루Ĭ��Ϊ�գ�
#      password:
#      # ���ӳ������������ʹ�ø�ֵ��ʾû�����ƣ�
#      jedis:
#        pool:
#          max-active: 8
#          # ���ӳ���������ȴ�ʱ�䣨ʹ�ø�ֵ��ʾû�����ƣ�
#          maxwait: 6000
#          # ���ӳ��е�����������
#          maxidle: 5
#          # ���ӳ��е���С��������
#          minidle: 1
